version: "2"

services:
  db:
    image: postgres:12.12-alpine
    ports:
      - "9876:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_USER: ####
      POSTGRES_PASSWORD: #####
      POSTGRES_DB: ####
    container_name: db
    restart: always
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: #############
      PGADMIN_DEFAULT_PASSWORD: ####
    ports:
      - "5050:80"
